name: Feature request
description: Suggest an enhancement to the provider
labels: ["kind/feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: The use case / pain point motivating the request.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
